### ISSUE TITLE
move to https://github.com/KiCad/Connectors_TE-Connectivity.pretty

### ISSUE THREAD

**Issue by pointhi** [KiCad/Connectors_TE-Connectivity.pretty#1]
because there are only TYCO connectors, and the company was renamed, we could move the footprints to https://github.com/KiCad/Connectors_TE-Connectivity.pretty

**Comment by evanshultz** [comment]
@pointhi Can this be closed now?

**Comment by SchrodingersGat** [comment]
Closing this issue - please reopen if you feel the need to @pointhi
